#show link: underline

= AIST5030 Mini-Project Report

== Introduction

In the mini-project, we finetuned a Small Language Model (SLM) to complete Fill-in-the-Middle (FIM) tasks resource-efficiently specifically for Rust, a modern, memory-safe programming language, using the parameter-efficient Orthogonal Finetuning (OFT) method. The source code of this mini-project is located at #link("https://github.com/hack3ric/oft-slm-rust").

== Methodology

=== Fill-in-the-Middle Tasks

Fill-in-the-Middle (FIM) is an advanced code completion task where a model learns to generate missing code by analyzing both the preceding and succeeding context, mimicking modern IDE autocomplete tools. A basic prompt structure used for FIM is shown in @fim-prompt, which includes the current open file's name alongside the code located immediately before and after the cursor, as visualized in @code-editor.

#block(height: 8em)[
  #set align(horizon)
  #grid(columns: (1fr,) * 2, column-gutter: 1em)[
    #figure(caption: "Example code editor state in an IDE")[
      #block(height: 8em)[
        #box(stroke: 1pt + gray)[#image("images/vscode.png")]]
    ] <code-editor>
  ][
    #figure(caption: "Derived FIM prompt")[
      #block(height: 8em)[#align(left)[
        #set text(font: "JetBrains Mono", size: 0.8em)
        #text(fill: blue)[\<filename>]main.rs\
        #text(fill: blue)[\<fim_suffix>]}\
        #text(fill: blue)[\<fim_prefix>]fn fibonacci(n: i32) -> i32 {\
        #text(fill: blue)[\<fim_middle>]
      ]]
    ] <fim-prompt>
  ]
]


=== Model, Dataset, and Configuration

This project utilized the _Qwen2.5-1.5B-Instruct_ model, a highly capable SLM, finetuned on the _Etherll/CodeFIM-Rust-Mellum_ dataset. This dataset contains approximately 57,000 FIM examples specifically designed for training intelligent Rust code completion.

We applied OFT targeting the model's attention and MLP layers with a rank of 8. The training was conducted using a learning rate of $2^(-4)$ over 2 epochs, culminating in 2,500 total steps to ensure steady convergence without overfitting.

== Experiment

=== Hardware and Data Setup

Training was executed on a single NVIDIA RTX 6000 Ada GPU. The dataset was partitioned into 40,000 items for the training phase and 6,920 items for quantitative evaluation.

=== Training

Training took approximately 4.5 hours and yielded a highly stable loss curve (@loss-curve), dropping from 1.2 to 0.5. The sharp decrease near step 1250 reflects a learning rate adjustment or epoch boundary, allowing the optimizer to quickly settle into a deeper minimum. Ultimately, the loss converged smoothly, confirming the OFT adapter successfully learned the FIM patterns without instability.

#figure(caption: "Training loss curve", placement: top)[
  #image("images/loss_curve.png", width: 40%)
] <loss-curve>

=== Qualitative Evaluation

To qualitatively evaluate the impact of OFT, we conducted a side-by-side manual comparative analysis of the code generated by the base Qwen2.5-1.5B-Instruct model and the finetuned model.

==== Example Output Comparison

We manually selected some outputs randomly and visually compare them. As we can see in @output-compare, the base model outputs long, verbose string that contains unwanted control sequences. On the other hand, the finetuned model produces short but valid results, confirming the finetuning improvement.

#figure(caption: "Example of errorneous base model output (left) vs correct finetuned model output (right)")[
  #block(height: 14em)[
    #grid(columns: 2, column-gutter: 1em)[
      #box(stroke: 1pt + gray)[#image("images/base_error_fim.png")]
    ][
      #box(stroke: 1pt + gray)[#image("images/finetuned_good_fim.png")]
    ]
  ]
] <output-compare>



//  Using the Hugging Face transformers and peft libraries, we performed controlled inference on a held-out set of Fill-in-the-Middle (FIM) test prompts to ensure both models received the exact same context. The generated outputs were then manually inspected to assess behavioral differences that automated metrics often overlook. Specifically, we examined each model's adherence to the expected FIM structural formatting, its context awareness regarding the provided prefix and suffix, and its overall verbosity versus conciseness. To assist in visually verifying the structural validity of these isolated snippets, we also utilized tree-sitter, a fast parsing library that constructs Abstract Syntax Trees (AST), allowing us to confirm whether the generated bridge code formed valid Rust logic when integrated back into the larger file.

// TODO: use tree-sitter to verify syntactic correctness

==== Statistics

We utilized tree-sitter @tree-sitter, a fast parsing library that constructs Abstract Syntax Trees (AST), to evaluate the output's syntactic correctness, allowing us to confirm whether the generated bridge code formed valid Rust syntax when integrated back into the larger file.

We measured Levenshtein distance between the output and ground truth, and computed the average edit ratio. Formula of Levenshtein edit ratio $R$ is as follows, with the size of test dataset $n$, a dataset row's prefix length $p_i$, suffix length $s_i$, model output length $m_i$, and Levenshtein editing distance $l_i$:

$
  R = 1/n sum_(i=1)^n l_i/(p_i + m_i + s_i)
$

We used the Hugging Face's `evaluate` library to calculate BLEU scores on the isolated generated snippets, which strictly measured n-gram string overlap against the ground truth. The results are shown in @results. As the data shows, we yield significantly better syntactic correctness

#figure(caption: "Statistical qualitative evaluation results (higher is better)")[
  #set text(size: 0.8em)
  #table(
    columns: 4,
    table.header([], [Syntactic Correctness], [Average Levenshtein Edit Ratio], [BLEU Score]),
    [Ground Truth], [0.7773], [-], [-],
    [Base Model], [0.0804], [0.1817], [0.0590],
    [Finetuned Model], [0.6046], [0.5729], [0.2891],
    [Improvement], [7.5x], [3.15x], [4.9x],
  )
] <results>

To evaluate deeper programmatic logic, we utilized a novel metric CodeBLEU @ren2020codebleu on the fully reconstructed files to assess structural integrity via AST matching and variable routing through data-flow analysis. The final CodeBLEU scores and its 4 individual components' scores are shown in @codebleu-scores. Since long prefixes and suffixes are stitched to model output, the original CodeBLEU scores are close to 1. Therefore, they are inverted using the formula $N' = 100(1 - N)$.

// #figure(caption: "CodeBLEU scores")[
//   #set text(size: 0.8em)
//   #table(
//     columns: 6,
//     table.header(
//       [], [CodeBLEU], [N-Gram Match], [Weighted N-Gram Match], [Syntax Match], [Dataflow Match],
//       [Base Model], [0.9088], [0.8792], [0.9816], [0.9506], [0.8237],
//       [Finetuned Model], [0.9701], [0.9774], [0.9828], [0.9783], [0.9419],
//       [Improvement], [1.06x], [], [], [], [],
//     ),
//   )
// ]

#figure(caption: "CodeBLEU scores (inverted, lower is better)")[
  #set text(size: 0.8em)
  #table(
    columns: 6,
    table.header(
      [], [CodeBLEU], [N-Gram Match], [Weighted N-Gram Match], [Syntax Match], [Dataflow Match],
      [Base Model], [9.12], [10.28], [1.84], [4.94], [17.63],
      [Finetuned Model], [2.99], [2.26], [1.72], [2.17], [5.81],
      [Error Reduction], [67.21%], [78.01%], [6.52%], [56.07%], [67.04%],
    ),
  )
] <codebleu-scores>

== Discussion and Limitations

=== Data Quality

The training dataset includes pre-alpha Rust code from as early as 2012, predating the stable 1.0 release in 2015. Because these snippets use deprecated, invalid syntax (as reflected by the ground-truth syntactic correctness results), the finetuned model also learned archaic patterns, limiting its ability to produce consistently correct, modern Rust code.

=== Vulnerability to Prompt Injection

We also identified a structural limitation in how the FIM templates are processed. Since code snippets are not sanitized or escaped, any raw text containing the control strings used for formatting (such as `<fim_middle>`) can accidentally act as a prompt injection, disrupting parsing and causing the model to start or stop generation at unintended positions rather than at the true prompt boundaries.

=== Semantic Correctness

While the finetuned model achieved high syntactic correctness, structural validity does not guarantee executable logic. Because the dataset consists of isolated snippets lacking full repository context, we could not test the generated code against the Rust compiler. Consequently, we were unable to evaluate the model's adherence to Rust’s strict semantic paradigms, such as borrow checking, variable mutability, and lifetime management.

These tasks are not conducted in this mini-project and remain future work.

== Conclusion


This project successfully demonstrated that OFT can efficiently adapt a 1.5B Small Language Model for specialized FIM code completion. The finetuned model significantly outperformed the base model in syntactic correctness, BLEU, and CodeBLEU metrics, proving finetuning improvements. Despite minor limitations caused by dataset noise and model capacity, the results validate OFT as a highly resource-efficient method for building domain-specific development tools.

// Table of Contents (TOC)

// 1. Introduction
// 2. Methodology
//     2.1 Model and Dataset Selection
//     2.2 Orthogonal Finetuning (OFT) Configuration
// 3. Experimental Results
//     3.1 Training Performance (Loss Curve)
//     3.2 Qualitative Evaluation (Before & After)
// 4. Discussion & Limitations
//     4.1 Format Adherence vs. Logical Generalization
//     4.2 Data Quality & Archaic Syntax
// 5. Conclusion

== References

#bibliography(title: none, "citations.bib")
